homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  packages: !include_dir_named packages

config:

http:
  base_url: !secret http_base_url
  login_attempts_threshold: 6
  ip_ban_enabled: true
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

updater:
  include_used_components: true

hacs:
  token: !secret github_access_token

discovery:

history:

logbook:

logger:
  default: warn

sun:

system_health:

tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
