sensor:
- platform: mqtt
  state_topic: monitor/ble/jacob
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: jacob_bluetooth
- platform: mqtt
  state_topic: monitor/ble/katelyn
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: katelyn_bluetooth
- platform: min_max
  name: "Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.jacob_bluetooth
    - sensor.katelyn_bluetooth

device_tracker:
- platform: mqtt
  devices:
    katelyn_bluetooth: location/bluetooth/katelyn
    jacob_bluetooth: location/bluetooth/jacob
