cover:
  - platform: template
    covers:
      garage_door:
        friendly_name: Garage Door
        value_template: >
          {{ (not is_state('sensor.garage_sr04_distance', 'unavailable')) and states('sensor.garage_sr04_distance')|float < 50 }}
        device_class: garage
        open_cover:
          service_template: "switch.turn_{{ 'off' if states('cover.garage_door') == 'open' else 'on' }}"
          data:
            entity_id: switch.garage
        close_cover:
          service_template: "switch.turn_{{ 'off' if states('cover.garage_door') == 'closed' else 'on' }}"
          data:
            entity_id: switch.garage

device_tracker:
  - platform: mqtt
    devices:
      jacob_car: 'location/car/jacob'

sensor:
- platform: template
  sensors:
    jacob_car:
      unit_of_measurement: '%'
      value_template: >-
        {% if is_state('device_tracker.jacob_car', 'home') %}
          100
        {% else %}
          0
        {% endif %}
- platform: mqtt
  state_topic: state/car/jacob
  name: jacob_car_state
