badnest:
  issue_token: !secret nest_issue_token
  cookie: !secret nest_cookie
  api_key: !secret nest_api_key

climate:
  - platform: badnest
    scan_interval: 10

sensor:
  - platform: badnest
    scan_interval: 10
